# Generated by Django 4.2.17 on 2025-04-05 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_id', models.UUIDField()),
                ('transport_method', models.CharField(max_length=10)),
                ('distance_value', models.FloatField()),
                ('distance_unit', models.CharField(max_length=5)),
                ('weight_value', models.FloatField()),
                ('weight_unit', models.CharField(max_length=5)),
                ('carbon_g', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('carbon_lb', models.FloatField()),
                ('carbon_mt', models.FloatField()),
                ('estimated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
