name: Run Unit Tests 

on: [push]

jobs:
  run-user-unit-tests:
    name: Run User Unit Tests
    runs-on: ubuntu-22.04

    steps:       
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
        
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run tests
        working-directory: backend
        run: python .\manage.py test